# Generated by Django 5.1.5 on 2025-02-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_address2_profile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
