# Generated by Django 5.1.5 on 2025-02-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adsress1',
            new_name='adsress',
        ),
    ]
