# Generated by Django 5.1.5 on 2025-02-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_adsress1_shippingaddress_adsress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='adsress',
            new_name='shiping_adsress',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='shiping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='shiping_country',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='shiping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='shiping_full_name',
        ),
    ]
